export { default as Home } from './Home';
export { default as Profile } from './Profile';
export { default as CreateCampaign } from './CreateCampaign';
export { default as CampaignDetails } from './CampaignDetails';
export { default as Website } from './Website'
export { default as About } from './About'
export { default as Contact } from './Contact'
export { default as HowItWorks } from './HowItWorks'
export { default as UserActivityTable } from './UserActivityTable'
export { default as Payment } from './Payment'